### ISSUE TITLE
I'm waiting for next streams...

### ISSUE THREAD

**Issue by shahindesu** [AzePUG/LiveStreamProjects#19]
Hi folks. I Really appreciate such kind of streams especially during lockdown and I hope see you guys soon with new streams :)

**Comment by ShahriyarR** [comment]
Hello Shahin,
Thanks for such tremendous support and love :)
Golang vs. Python REST API series is nearly over and there is only 1 remaining task to explore - Deployment of our shitty API.
But unfortunately, especially I have no time nowadays. But we will do it for sure.
